apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: cloud-console
  name: cloud-console
spec:
  chart:
    name: cloud-console
    repository: https://openinfradev.github.io/hanu-helm-repo
    version: 1.0.0
  releaseName: cloud-console
  targetNamespace: fed
  values:
    config:
      extra:
        config: ""
        sql: |-
          /* INSERT CLUSTER AND MENU DATA FOR SKB-DOJ-DEV */
          INSERT INTO "cluster" VALUES ('siim-dev','http://taco-kibana-dashboard-kb-http.lma.svc.siim-dev:5601','http://lma-grafana.fed.svc.siim-dev','https://kubernetes.siim-dev:6443','eyJhbGciOiJSUzI1NiIsImtpZCI6IjRhZDRQYVR2SFZPNzQtMmVZcU1ITGtJeE1nc3RMTVA0blpvMDhxQ2k5TTAifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJmZWQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoidGFjby13YXRjaGVyLXNhLXRva2VuLXFxdGxzIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InRhY28td2F0Y2hlci1zYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjNhNzQ0ODVkLWQ0ODgtNGI4ZC04MWNmLWQ1ZDBmNWRiOWVlNSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpmZWQ6dGFjby13YXRjaGVyLXNhIn0.b66hUB3_j4pmA3g1DQwI8-xn-dYgKzlYMt0ggJsHPwTqf5KmbMHGlgffgPhJq4D_SgxzDrVBhQvsz0cd0J2xhXuCBuWHJQJ3adk8RkW92LzmYD5tOpQTNZ2zpKVwS50n01lU50oSd1U9UW2Fh_ckr-jcdJFTVyNjV7KW3b6Reo5rl9_CYCTKWg21lHT0pm_OcLsOg2C67vXqFADI7iV1e4wpPIg8Ikt-sd-kd07Ni6BsaCEk1jwFnHY54DZhvZuK5iK7ePIUUWgu5i16lCwq6PuIQVROxEre2fDWr7m8yCda2zqTeGNPFUTenGhclfzXcvZYbtPjZB0P21yc4-ujIQ',1,'grafana','/d/_IOiw2TWz/cluster-status-taco?orgId=1&refresh=10s','grafana','/d/Us97AHbWz/pod-status-taco?orgId=1&refresh=10s','grafana','/app/canvas#/workpad/workpad-57011c4b-16e5-4167-967a-8b3046547f8d/page/1?__fullscreen=true','grafana','/app/canvas#/workpad/workpad-57011c4b-16e5-4167-967a-8b3046547f8d/page/1?__fullscreen=true', 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EY3dNakV3TlRVMU1Wb1hEVE13TURZek1ERXdOVFUxTVZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTGc3CkpmSkJmSW1KN2VCQjVlb2FMRC9YRlNZWWRGKzduT2JPT2s1cnk4cUhaVVk2UzlETDJicXpXdVNMdE1nYUgySE4KVDViajNxbmlaTzhRdGJvc1lpOUM4ODdrcjVuRjc5TkdzcFRzbFpiUG5OV28zTGZLRDZhKzlNQ1oreU82T05xeAphNEg2eDhpbGNIeU5YbHNSVktBNG9KaGNJMlRoRmNMdTNXcURqanFvSkwrSzk0ZVlFS3hZYTdHKzlwTmF4VFZ2CkVzYUJyQjhEd2xhNkxkSU5EU1V0THZvMjVCWkdyaXF1T2Y0OEYxYTlGNFI1V21weTBacXZMZkZsaHhNeGp4MVEKNjFEcm1FdVNZQ0FpQ01ndCtyUmZRWmovUjhsTUZjVVl4OWVtanhmVHYrUFFKd1dzOHg5OXlwSzZGYkdPU3o3SQpwZFlybitySjdPRnpnNm5oMWdFQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFMVGdHMnVKdW9ub2g4Ly8yaGQ2OGhKT0MwYmIKbnJpRys3V2pVbkwrUWpzSlFqTk5YbXJid3dlb1JrajVDaVJxeUFhazYxZmIrdFVxcTJjcGw4eVM5c2JkeCtJSQpxdWdneVR5cjZYRnl4aTlkVE9Ya3RDZnJINGs0VlYyZmM3MFp0K3F1NEk0Nk1BSnVNa2RNQmRuRVM0SmhVR21OCllZS1RGTmxCSHJMa2E0T1B4dGRQbWNPbUFmd1VXSTVsV3RzVWN0Q0J6bzcrZWp1M1BUbC9sR0JHbXRJSFl1bDYKcnRzbGErbjloSi9qREs3S1ovMS9NN2hzeERuSC9ZeEhQcTRRWkNjMEE5VDFmRkpSd002cThDbVNodlNuOVRKRQpaNENXREVJRUl0dzhyM3ppeWlrMlExUmR0MVlXWFUzR2Q3SDJiRi9SVW9MaVlQdTZkblVRWmRuKzd3Zz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=');
          INSERT INTO "cluster_menu" VALUES ('siim-dev',1,0,'Kubernetes',1,NULL,NULL,NULL,0);
          INSERT INTO "cluster_menu" VALUES ('siim-dev',2,1,'Cluster Status',2,'/d/_IOiw2TWz/cluster-status-taco?orgId=1&var-taco_cluster=siim-dev','grafana','embedded',1);
          INSERT INTO "cluster_menu" VALUES ('siim-dev',3,1,'Node Status',3,'/d/tKgHHwoWk/node-status-taco?orgId=1&var-taco_cluster=siim-dev','grafana','embedded',1);
          INSERT INTO "cluster_menu" VALUES ('siim-dev',4,1,'Host Status',4,'/d/okotUJJWz/hosts-status-taco?orgId=1&var-taco_cluster=siim-dev','grafana','embedded',1);
          INSERT INTO "cluster_menu" VALUES ('siim-dev',5,1,'Pod Status',5,'/d/Us97AHbWz/pod-status-taco?orgId=1&var-taco_cluster=main','grafana','embedded',1);
          INSERT INTO "cluster_menu" VALUES ('siim-dev',6,1,'Node Network',6,'/d/l1jN0FAZz/node-network-detail-taco?orgId=1&var-taco_cluster= siim-dev','grafana','embedded',1);
          INSERT INTO "cluster_menu" VALUES ('siim-dev',7,1,'Compute Resource',7,'/d/l1jN0FAZz/node-network-detail-taco?orgId=1&var-taco_cluster= siim-dev','grafana','embedded',1);
          INSERT INTO "cluster_menu" VALUES ('siim-dev',8,0,'NextPass Dashboard',8,NULL,NULL,NULL,1);
          INSERT INTO "cluster_menu" VALUES ('siim-dev',9,8,'Cluster Status',9,'/d/SHuJaTWMk/01-cluster?orgId=1','grafana','embedded',1);
          INSERT INTO "cluster_menu" VALUES ('siim-dev',10,8,'Pod Status',10,'/d/_NanfTZMk/02-app?orgId=1','grafana','embedded',1);
          INSERT INTO "cluster_menu" VALUES ('siim-dev',11,8,'Namespace Status',11,'/d/1YHjfoWMz/03-namespace?orgId=1','grafana','embedded',1);
          INSERT INTO "cluster_menu" VALUES ('siim-dev',12,8,'Node Status',12,'/d/80bIYTWGz/04-node?orgId=1','grafana','embedded',1);
          INSERT INTO "cluster_menu" VALUES ('siim-dev',13,8,'Summary',13,'/d/HicqYoZGk/05-summary?orgId=1','grafana','embedded',1);
          INSERT INTO "cluster_menu" VALUES ('siim-dev',14,8,'Control Manager & API',14,'/d/rfwMPoWGz/06-k8s-control-plane-manager?orgId=1','grafana','embedded',1);
          INSERT INTO "cluster_menu" VALUES ('siim-dev',15,8,'K8S ETCD',15,'/d/wvirETZGz/07-k8s-control-plane-etcd?orgId=1','grafana','embedded',1);
          INSERT INTO "cluster_menu" VALUES ('siim-dev',16,8,'K8S - Scheduler',16,'/d/CLKUL4GMz/08-scheduler?orgId=1','grafana','embedded',1);
          INSERT INTO "cluster_menu" VALUES ('siim-dev',17,8,'K8S CoreDNS',17,'/d/kp3SsTWMk/09-coredns?orgId=1&refresh=10s','grafana','embedded',1);
          INSERT INTO "cluster_menu" VALUES ('siim-dev',18,8,'K8S Proxy',18,'/d/ioHKsoWMz/10-k8s-proxy?orgId=1','grafana','embedded',1);
          INSERT INTO "cluster_menu" VALUES ('siim-dev',19,0,'Network',19,NULL,NULL,NULL,1);
          INSERT INTO "cluster_menu" VALUES ('siim-dev',20,19,'Calico',20,'/d/pF9vmrTWz/calico?orgId=1&var-taco_cluster=siim-dev','grafana','embedded',1);
          INSERT INTO "cluster_menu" VALUES ('siim-dev',21,19,'Felix Dataplane',21,'/d/3RDlWZAZk/kubernetes-calico-taco?orgId=1&var-taco_cluster=siim-dev','grafana','embedded',1);
          INSERT INTO "cluster_menu" VALUES ('siim-dev',22,0,'Discovery',22,'/app/kibana#/discover?_g=()&_a=(columns:!(_source),index:a5c5da70-2885-11ea-bc14-058cf5a7efd0,interval:auto,query:(language:kuery,query:''''),sort:!(!(''@timestamp'',desc)))','kibana_dash','embedded',1);
          INSERT INTO "cluster_menu" VALUES ('siim-dev',23,0,'Admin Console',23,'/EmptyLink','adminConsole','embedded',1);
          INSERT INTO "main_menu" VALUES ('siim-dev','Y','N','N','N');
      filter:
        rule: "yes"
      grafana:
        authkey: admin:password
      initDB: true
      keycloak:
        cacert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURSekNDQWkrZ0F3SUJBZ0lKQU41dFhpR1gvR0dqTUEwR0NTcUdTSWIzRFFFQkN3VUFNRG94Q3pBSkJnTlYKQkFvTUFrbFVNU3N3S1FZRFZRUUREQ0pyWlhsamJHOWhheTV6YTJJdFpHOXFMV1JsZGpBeExtSjBkbkJoWVhNdQpZMjl0TUI0WERUSXdNRGN3TXpFd01UVXlPRm9YRFRNd01EY3dNVEV3TVRVeU9Gb3dPakVMTUFrR0ExVUVDZ3dDClNWUXhLekFwQmdOVkJBTU1JbXRsZVdOc2IyRnJMbk5yWWkxa2Iyb3RaR1YyTURFdVluUjJjR0ZoY3k1amIyMHcKZ2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzI3bGkzTEpQVEY2cm1yOU15Q0Y3SgpGQkIyZkwzYVYxbU9TUVJPckovb25FUzBtd25uZUFKYkw2Q044SVlZVlZ3QXZYWmlwY0RKa1ZTNVgySUNlajI0CmJlUUFPcGxwOFFKaXZYMmJpelp3QU9JTGcxdFFBTkhHY1VsQXVRZzBmYmhYYWhZcGllbDJqc3BERFNoWXJNYUQKR1haTS9YdnkyL0R6M29VNHJqeFZUckZhdW1mZFhTTjdpSGp3REJtd3d5dVZaWThzWHlURGdCS2Yxd0pQcVFzdgpUSlIvb0ZRTm8zbDNhSlBWUDEwd2JSMkJRc3NFSTQ4K203bFhRUkZpRzFtbFFoOFYvNXg3YnlyZjlscmtkeDRlClRmRnMvd3cyUWhHUTJQcExkSDVDdTJTcnI5aDVkMG1tZG9YL083aDgvRm1iNitkMXhWMDNkWGJIRXpsdlFFcGQKQWdNQkFBR2pVREJPTUIwR0ExVWREZ1FXQkJTU1d0YjJCc2lxbGtwVlV4c09hcSs0WGpxM3pEQWZCZ05WSFNNRQpHREFXZ0JTU1d0YjJCc2lxbGtwVlV4c09hcSs0WGpxM3pEQU1CZ05WSFJNRUJUQURBUUgvTUEwR0NTcUdTSWIzCkRRRUJDd1VBQTRJQkFRQlVLa2FlRjJlUHIwaG0ycmxrTnhoWCs0cFpGeHB1cmV3L042MmVVN1NDOHFRK1ZiUjIKM0F6M0c5bnozMnM2YTZkalYzUmdsSjk1dkxiRlhONk5kNHpOTWpsRkFDNjdJdFBLODBHc1ZQbVkxRUYzdlRsSQpKcmMyck4zeUNjRjAyQ3NwMUhIVFlNa3ptNndXeUtUVzE0dDlMY0JxUVJiZytSMURKTW5iNXJZdCtoS0Rlc2ltCkROb0tKVWlybCtDSnNqS2xOYVg3UjZYdXNoOHRLRWRSdUVKZ1lkM2d3dms3ejJuS2hyMGQxQUI5Y2VCcldNckIKVW9qMmZMMGdUQkl4dWJBdmhMcThWdjNlTzNRZ0ZkeEVSSWQrMWpzaExEQ1IwUzM3dHhnbUE2OEc0YldEdnpSYQpEQ2syb1E5eDF1Z0xNVGQvUGpLSmZzNlpzbHA5SFVTSGpEYlgKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        clientId: cloud-console
        enabled: "yes"
        hasRealmRole1: lma_system
        hasRealmRole2: lma_app
        hasRealmRole3: lma_viewer
        realm: siim-dev
        url: https://192.168.5.61:30003/auth
      kibana:
        authkey: elastic:tacoword
      lenz:
        url: http://192.168.5.200:8080
      loggingfilter:
        url: /apis/logging.kubesphere.io/v1alpha2/namespaces/lma/filters/kubernetes
      password: password
      prometheus:
        ruleUrl: /apis/monitoring.coreos.com/v1/namespaces/fed/prometheusrules
      service:
        proxyportlist: 32001-32008
        proxyurl:
          format: mydev:%REQUEST_PORT%
      username: taco
    image:
      pullPolicy: Always
      repository: siim/taco-cloudconsole
      tag: 200721
    ingress:
      enabled: false
    nodeSelector:
      taco-lma: enabled
    service:
      nodePort: 32000
      port: 32000
      proxy_from: 32001
      proxy_to: 32008
      targetPort: 32000
      type: ClusterIP
    volume:
      storageClassName: rbd
      accessModes: ReadWriteOnce
  wait: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  labels:
    name: keycloak
  name: keycloak
spec:
  chart:
    name: keycloak
    repository: https://openinfradev.github.io/hanu-helm-repo
    version: 8.2.2-skt03
  releaseName: keycloak
  targetNamespace: fed
  values:
    clusterDomain: siim-dev
    global:
      storageClass: ceph
    keycloak:
      extraEnv: |
        - name: KEYCLOAK_LOGLEVEL
          value: WARN
        - name: WILDFLY_LOGLEVEL
          value: WARN
      ingress:
        enabled: false
        hosts:
        - keycloak.example.com
        tls:
        - hosts:
          - keycloak.example.com
          secretName: tls-keycloak
      password: password
      persistence:
        dbPassword: password
        dbUser: keycloak
        dbVendor: postgres
        deployPostgres: true
      service:
        extraPorts: ""
        httpNodePort: ""
        httpPort: 80
        httpsNodePort: ""
        httpsPort: 8443
        jgroupsPort: 7600
        nodePort: "32080"
        type: NodePort
    postgresql:
      persistence:
        enabled: false
        size: 5Gi
        storageClass: rbd
      postgresqlDatabase: keycloak
      postgresqlPassword: password
      postgresqlPostgresPassword: password
      postgresqlUsername: keycloak
  wait: true
